[env]
_.path = ['{{config_root}}/node_modules/.bin']

[tasks.dev]
description = "Run the development bundler"
run = "tsdown --watch"

[tasks.build]
description = "Build the library"
sources = ["../../pnpm-lock.yaml", "tsdown.config.ts", "tsconfig.json", "src/**/*.ts"]
outputs = ["dist"]
run = "tsdown"

[tasks.fmt]
description = "Format the entire project"
run = "prettier --write ."

[tasks.lint]
description = "Lint the entire project"
run = "biome lint --write --unsafe --assist-enabled=true ."

[tasks.fix]
description = "Format and lint the entire project"
depends = [":fmt", ":lint"]

[tasks.typecheck]
description = "Typecheck the entire project"
run = "tsgo --noEmit"
